services:

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.4.4
    restart: always
    command: --overprovisioned 1 --smp 1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --execute 'SELECT now() from system.local;'"]
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - 9042:9042
    networks:
      web:

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:5.4.4
    restart: always
    command: --seeds=scylla-node1 --overprovisioned 1 --smp 1
    depends_on:
      scylla-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --execute 'SELECT now() from system.local;'"]
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - 9043:9042
    networks:
      web:

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:5.4.4
    restart: always
    command: --seeds=scylla-node1 --overprovisioned 1 --smp 1
    depends_on:
      scylla-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --execute 'SELECT now() from system.local;'"]
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - 9044:9042
    networks:
      web:

networks:
  web:
